### PR TITLE
Add macOS build

### LINKED ISSUE #76: macOS
plz

### PR DESCRIPTION
**Pull request by cschlosser**
Closes #76 

There is still some weird things on macOS like when using dark mode the file tab text is "bright on bright" but this PR should focus on having a working macOS build.

### CODE REVIEW

**Comment by dail8859** [comment]
Awesome! I'll take a look more at this hopefully later today.

> PR should focus on having a working macOS build.

Yes I completely agree. I'd rather have something usable rather than waiting for something perfect.

**Comment by mcoolidge** [comment]
FWIW: I just tested this and it builds and runs well! 

but the app is missing the icon for some reason. 
CleanShot 2022-04-10 at 11 12 21@2x

**Comment by cschlosser** [comment]
Did you build it locally?
If yes you will have to run these steps as well: https://github.com/dail8859/NotepadNext/pull/83/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R82-R88
The copyright holder of the image file should be able to upload a .icns file to the repository.

**Comment by dail8859** [comment]
@cschlosser 

> The copyright holder of the image file should be able to upload a .icns file to the repository.

Are you referring to the SVG file? I created it. Is it easiest to include the icns file you generated in the repository as well? That would remove the dependency on inkscape etc

**Comment by cschlosser** [comment]
I'm very careful with (re)uploading media and other art with git's unfortunate terminology of authorship in this context. If you created the .svg @dail8859 I would prefer if you could upload the .icns file, you should have write access to my PR.

**Comment by dail8859** [comment]
@cschlosser

> I would prefer if you could upload the .icns file

No worries. Will do.

**Comment by dail8859** [comment]
Added the icns file. The build checks worked for me but seems it failed in your repo...weird.

**Comment by cschlosser** [comment]
Thank you, it works for me

**Pull request merged**
