### PR TITLE
Add metainfo and linux screenshot for Flatpak distribution

### PR DESCRIPTION
**Pull request by zocker-160**
This is the first step towards #84 and adds a metainfo xml file, which is used to generate the store appearance for Flathub.org including all the software stores that use it.

It is a draft / template, because I have not filled everything, so please fill `<description>` and `<url>` to your liking. You can of course also add more tags as documented here:
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

I would like to add, that in order to make the Flatpak work, I need a (new) tag which includes 5b9a8cef449cb0de0b59fd778c4e5a9703de80f6, because otherwise pulling the submodules fails.

EDIT: PR is against the `linux-build` branch, because I think that is appropriate, if you want me to do it against a different branch, pls let me know.

### CODE REVIEW

**Comment by dail8859** [comment]
@zocker-160 

Thanks for the PR! 

> It is a draft / template, because I have not filled everything

No problem. When I get some more time I'll look into it more.

> I need a (new) tag which includes https://github.com/dail8859/NotepadNext/commit/5b9a8cef449cb0de0b59fd778c4e5a9703de80f6

I hope to do a release before _too_ long, especially now that macOS builds are available. And hopefully that release will have everything in order for a flatpak distribution as well.

> PR is against the `linux-build` branch

Once I get confirmation that PR #78 does fix #77 then that's fine.

**Comment by zocker-160** [comment]
> Once I get confirmation that PR https://github.com/dail8859/NotepadNext/pull/78 does fix https://github.com/dail8859/NotepadNext/issues/77 then that's fine.

Understood, I could try that on RHEL8 as well if you just want a confirmation if it works.

Regarding the branch, I think you will have to rebase it onto master either way before merging.

**Comment by dail8859** [comment]
> Understood, I could try that on RHEL8 as well if you just want a confirmation if it works.

That would be helpful if you get a chance. Was hoping the originator of that issue would confirm since I don't want to merge anything without knowing for sure.

More-so for my own reference for later...here's a mature Qt project that also has the metainfo and flatpak distribution...

https://github.com/mapeditor/tiled/blob/ea32425119852ebb05227e6149a0d9e63b3b81cb/org.mapeditor.Tiled.appdata.xml

https://flathub.org/apps/details/org.mapeditor.Tiled

**Comment by zocker-160** [comment]
> More-so for my own reference for later...here's a mature Qt project that also has the metainfo and flatpak distribution...

Yeah it is always a good idea to see how other projects are doing it.

The metainfo above is very barebones to get you started, I thought that might be helpful.

**Comment by dail8859** [comment]
> The metainfo in the PR is very barebones to get you started, I thought that might be helpful.

It is much appreciated! 😄

**Comment by dail8859** [comment]
Made a quick update. I have no idea what to put for a description. I'm not good at that kind of fancy stuff. I prefer monospaced fonts for all my powerpoint slides. 😆

**Comment by zocker-160** [comment]
I am really bad at that as well :laughing: .

When looking at the description of other applications, it would be ok I think. You can update it anytime later anyway.

some examples for reference:

- https://flathub.org/apps/details/org.kde.kwrite
- https://flathub.org/apps/details/org.gnome.gedit
- https://flathub.org/apps/details/com.github.alexkdeveloper.notepad
- https://flathub.org/apps/details/io.posidon.Paper

**Comment by dail8859** [comment]
> You can update it anytime later anyway.

Yeah if someone ever comes up with a better catchy description that's fine.

**Comment by zocker-160** [comment]
awesome, so now I only need a new tag and then I can create the submission request for Flathub.

PS: I created a post on reddit, which will hopefully help us with #77. ;)

**Comment by dail8859** [comment]
> so now I only need a new tag and then I can create the submission request for Flathub.

I'm currently working on the build system and github action to streamline a bit of the release process then hope to do a new release once that's in place.

> PS: I created a post on reddit

Nice!

**Pull request merged**
