### PR TITLE
Create NotepadNext.sv_SE.ts

### PR DESCRIPTION
**Pull request by eson57**
Add Swedish translation, please.

### CODE REVIEW

**Comment by dail8859** [comment]
@eson57 Awesome! Thanks for the PR. There's a couple other places I'll need to adjust before merging to include the translation but you did the hard work :) I'll try to merge this in sometime today.

**Comment by dail8859** [comment]
@eson57 

Can you try downloading one of the artifacts for Qt 5.15 [here](https://github.com/dail8859/NotepadNext/actions/runs/2539221843). Just want to make sure it is working as expected for you.

**Comment by eson57** [comment]
Sorry, I've never understood how to download artefacts. Can't find any download links. Please explain. I'm exclusively on Linux, btw.

**Comment by dail8859** [comment]
No problem. At the bottom of that page I linked are artifacts. Since you are using Linux you can download a zip of the AppImage directly [here].(https://github.com/dail8859/NotepadNext/suites/7033584479/artifacts/276690140)

If you are not familiar with AppImage at all, its just like an executable. Once you extract it, you'll have to `chmod +x` the file then just run it like any other exe. It won't affect any existing Notepad Next on your system.

**Comment by eson57** [comment]
Stupid me. I didn't even notice it was a scroll page. Well, AppImage I use all the time so that's not a problem, however this particular appimage  do not run with Swedish gui. Translation seem not to work.

**Comment by dail8859** [comment]
Can you post the terminal output of the application startup? It should log enough information to show what translation it is trying to load.

**Comment by eson57** [comment]
eson@EngN1-1:~/.local/bin$ ./NotepadNext-x86_64.AppImage
[     0.159] I: =============================
[     0.159] I: NotepadNext v0.5.2
[     0.159] I: Build Date/Time: Jun 22 2022 01:10:37
[     0.159] I: Qt: 5.15.2
[     0.159] I: OS: Linux Mint 20.3
[     0.159] I: Locale: sv_SE
[     0.159] I: CPU: x86_64
[     0.159] I: File Path: /tmp/.mount_NotepaPxCREC/usr/bin/NotepadNext
[     0.159] I: Arguments: /tmp/.mount_NotepaPxCREC/AppRun.wrapped
[     0.159] I: =============================
[     0.159] I: sv_SE translation not found for NotepadNext
[     0.159] I: sv_SE translation not found for QT components
[     0.159] I: bool NotepadNextApplication::init()
[     0.159] I: LuaState::LuaState()
[     0.177] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.214] I: setupUi Completed
[     0.254] I: void MainWindow::setupLanguageMenu()
[     0.262] I: void MainWindow::restoreSettings()
[     0.262] I: void NotepadNextApplication::applyArguments(const QStringList&)
[     0.262] I: void MainWindow::newFile()
[     0.263] I: void EditorManager::setupEditor(ScintillaNext*)
[     0.265] I: void MainWindow::addEditor(ScintillaNext*)
[     0.265] I: void MainWindow::detectLanguage(ScintillaNext*)
[     0.265] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[     0.265] I: Language Name: Text
[     0.265] I: void DockedEditor::addEditor(ScintillaNext*)
[     0.319] I: void MainWindow::activateEditor(ScintillaNext*)
[     0.319] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[     0.319] I: void MainWindow::updateGui(ScintillaNext*)
[     0.319] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
[     0.319] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[     0.319] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
[     0.319] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)

**Comment by dail8859** [comment]
Thanks for the info.

Looks like this PR is correct, but there's an existing issue that the translations have not ever been included in the AppImage. Looks like they are there for Windows as far as I can tell. I'll merge this PR and open a separate issue.

**Comment by eson57** [comment]
Well I was quite excited when I found your app, as I ones was on Windows and used Notepad++ very frequently. Plese ping me when you need translation updated.
I hope you will implement split window, side by side tabs.  :)

**Comment by dail8859** [comment]
> split window, side by side tabs

What do you mean exactly? I think some of what you are looking for is possible already.

**Comment by eson57** [comment]
They call it "Dual View" in Notepad++
https://npp-user-manual.org/docs/images/move2view.gif

**Comment by dail8859** [comment]
You can drag and drop tabs in Notepad Next already (unless something isn't working on Linux). Works a little differently that Notepad++. This even supports multiple views:

img

**Pull request merged**
