### PR TITLE
add initial debian/ dir

### PR DESCRIPTION
**Pull request by bgstack15**
Intended for use on Debian-based systems. I built this on a Devuan Ceres (Debian Sid aka unstable) system. Anyone can use this as a base for building a package on similar platforms.

### CODE REVIEW

**Comment by dail8859** [comment]
Thanks for the PR!

I'll need quite a bit more context on this PR exactly since I'm not a Debian user at all. There is a flatpak distribution in the works and I'm not sure if this will support Debian or not.

@zocker-160 can you comment on whether the flatpak will be available for Debian-based systems?

I want to be careful about how much maintenance burden there is with all the different build systems. Plus any additional burden of creating/testing/publishing a release. 

The current release is for Qt5 and this looks like Qt6. Its starting to introduce quite alot of variations in the releases which could make debugging and troubleshooting difficult.

**Comment by bgstack15** [comment]
I know the build dependencies include some qt6 stuff. Those were necessary to build, probably because of qmake6. I don't know if qmake6 is directly related to qt6. Interestingly enough, the auto-resolved install-time dependencies were only:
```
 Depends: libc6 (>= 2.32), libgcc-s1 (>= 3.0), libqt5core5a (>= 5.15.1), libqt5gui5 (>= 5.14.1) | libqt5gui5-gles (>= 5.14.1), libqt5network5 (>= 5.0.2), libqt5printsupport5 (>= 5.0.2), libqt5widgets5 (>= 5.15.1), libstdc++6 (>= 11), libxcb1
```

**Comment by zocker-160** [comment]
> can you comment on whether the flatpak will be available for Debian-based systems?

@dail8859 As explained in [my comment](https://github.com/dail8859/NotepadNext/issues/84#issuecomment-1095441039) in #84, Flatpak is supported by basically all major distributions out there, including Debian starting from Debian 8 (Jessie) from 2015.

see: https://en.wikipedia.org/wiki/Flatpak#Supported_out-of-the-box
and: https://www.flatpak.org/setup/

**Comment by dail8859** [comment]
@zocker-160 

> Flatpak is supported by basically all major distributions out there

That's what I was thinking but wanted to make sure. 

@bgstack15

Thanks again for the PR but it seems flatpak will solve the need for a Debian specific distribution so I'll close this PR for now. If there's something I'm missing we can still discuss it, but there would have to be some major compelling reason to have something Debian specific since flatpak will cover nearly all major distributions.

**Pull request closed without merging**
