### PR TITLE
Added the option to comment/uncomment lines of code.

### PR DESCRIPTION
**Pull request by Satharus**
Implemented the feature request in #107.

I set the shortcuts to Notepad++'s defaults. Although most text editors use Ctrl + / -which I also prefer- but I think since this is a reimplementation of Notepad++ we should try to stay as close to it as possible. Maybe we can make shortcuts configurable later on!

### CODE REVIEW

**Comment by dail8859** [comment]
Thanks for the PR!

I haven't tried compiling running the code yet, but had some initial thoughts.

- I'd like to keep any language specific settings out of the MainWindow class. The MainWindow class is already larger than I'd like. Ideally these would go in each of the Lua files for each language. The grand plan is it should easy to add a new language and touch as few files as possible. (Notepad++ takes a modification of at least 10 files to add a new language).
- The actually commenting/uncommenting logic probably needs to go else where. Other parts of the code shouldn't be dependent on a MainWindow in order to trigger this behavior. Once you have an editor and a comment string, there's really nothing else you need...so this logic would probably be best put in the ScintillaNext class since it is very decoupled from the MainWindow.

> I think since this is a reimplementation of Notepad++ we should try to stay as close to it as possible

To be fair I'm not looking for a completely _pure_ reimplementation, so if there are changes that make sense, especially if the industry standard is different, now is the time to do them.

> Maybe we can make shortcuts configurable later on!

Definitely would be nice at some point!

**Comment by Satharus** [comment]
Thanks for the feedback! Sorry for the late response I've been a bit busy the past 2 days and hadn't had the time to logon here.


> To be fair I'm not looking for a completely pure reimplementation, so if there are changes that make sense, especially if the industry standard is different, now is the time to do them.

Alright that totally makes sense I went ahead and changed the toggle comment to Ctrl+/ which is the default on most editors. I had to change the Reset Zoom shortcut to Ctrl+0 as it was originally set to Ctrl+/.

>  This logic would probably be best put in the ScintillaNext class since it is very decoupled from the MainWindow.

Done.

> Ideally these would go in each of the Lua files for each language.

Also done!

**Comment by dail8859** [comment]
> Sorry for the late response

No problem at all. Everyone else has real lives outside of GitHub :)

Just glanced through the code real quick and that looks much better. When I get some time myself I'll go through the code in more detail.

**Comment by Satharus** [comment]
Awesome! I am awaiting your review. 

Thanks!

**Comment by dail8859** [comment]
I pushed some initial code changes.

- Remove need for `singleLineComment` in languages that don't have comments
- Removed explicit calls to `this->` and `ScintillaEdit::`
- Removed unneeded `singleLineCommentCharacters` member

A few things I noticed:
- This code only works for a single line, you can't select a range of lines like Notepad++
- Notepad++ uses a space after each character e.g. in C++ it comments a line starting with `// ` so I'm not sure if the code should add a space internally or if the `singleLineComment` should contain the space
- It would be nice to try to avoid creating a new `QString` for each line, especially if/when the code supports it, but I'd have to look at the code more to see if there's a better option.

If you feel like making the changes that's perfectly fine, if not I can take what you got and work from there.

Thanks

**Comment by Satharus** [comment]
Awesome! Thanks for the cleanup. :smile: 

> This code only works for a single line, you can't select a range of lines like Notepad++

Well, yes, that's what I really had the time to implement for now, sadly. I am willing to contribute more to this project later on because I truly love the idea! I love notepad++ and how light it is and I was upset that it isn't available on Linux, since it is my main daily driver. So this project really is a Godsend hahahah

> Notepad++ uses a space after each character e.g. in C++ it comments a line starting with // so I'm not sure if the code should add a space internally or if the singleLineComment should contain the space.

I think we should add the space through the code, as the single line comment string doesn't actually contain the space as per each language's specifications. So I don't think it should be in the language file itself. That's just my opinion, though.

> It would be nice to try to avoid creating a new QString for each line, especially if/when the code supports it, but I'd have to look at the code more to see if there's a better option.

I guess there could be a way to look if the line has a comment string at the start using Scintilla functions without having creating a QString, but I'm not really sure what it could be tbh.

**Comment by dail8859** [comment]
> Well, yes, that's what I really had the time to implement for now, sadly

Totally understandable.

> So I don't think it should be in the language file itself. That's just my opinion, though.

I guess I'd be more of the opinion to put the extra space in the `singleLineComment` variable that way a language could optionally include it or not. However since adding the space through code has worked well for the Notepad++ project then I guess it has never been an issue. So I'm fine doing it in code. Worst case scenario we find there is a particular language or something that shouldn't have the space and change it later.

> but I'm not really sure what it could be tbh.

I know there's way to find how far a line is indented so not sure if that could be used to see if the comment string is at that position. I haven't looked at the Notepad++ code to see how it does it there. I might be trying to prematurely optimize this section of code...I tend to overthink things.

The reason I'm a bit cautious about the QString() is because there could be cases of really long lines, or if the user selects *alot* of lines. Though I guess this would be an interesting case to profile to see just what kind of performance the two implementations would have...but if there's no other easy/obvious solution QString is fine until there's a reason to implement it otherwise.

**Comment by Satharus** [comment]
> I guess I'd be more of the opinion to put the extra space in the singleLineComment variable that way a language could optionally include it or not.

Your project, your code! I think both options work just fine :smile: 

Thanks a lot for your efforts!

**Comment by dail8859** [comment]
I was working with this code yesterday. I made some improvements but there's one issue that seems rather difficult to handle. When you insert the comment string, the selection is lost. Notepad++ handles this but the code is a bit of a mess to track the correct location.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f6ade2c9157e7c6a56c95dfd04c436df512ca028/PowerEditor/src/Notepad_plus.cpp#L4980

**Comment by Satharus** [comment]
> When you insert the comment string, the selection is lost.

I really didn't notice that when implementing it hahahaha ..

You're right though, I am not sure if we should mimic NP++'s code or if there is a smarter implementation :thinking:

**Comment by dail8859** [comment]
Pushed a change which should handle the selection information. I very briefly tested this and it seems to give be similar behavior to Notepad++. Sure it needs more testing/tweaking.

**Comment by dail8859** [comment]
The code isn't too messy. I don't like the repeated sections of code. I'll try to come up with a better way.

**Comment by dail8859** [comment]
I refactored the code quite a bit. It is better than it was and seems to give correct behavior.

**Comment by Satharus** [comment]
The code looks much better!

I gave it a test and it seems to be working perfectly fine. :muscle: :tada:

**Comment by dail8859** [comment]
Apologies for the delay.

Thanks so much for the PR! Glad to see this functionality in the application. Best I can tell it works nearly identical to Notepad++ other than one minor difference...but I'll wait to see if anyone ever notices :)

**Comment by Satharus** [comment]
Thanks for merging! Really happy to finally see some of my code become part of this project :smile:

**Pull request merged**
