### PR TITLE
fix missing icon in titlebar and taskbar

### PR DESCRIPTION
**Pull request by zocker-160**
_last PR for today, I hope I am not annoying with all those PRs :P_

I am not sure if this is a Linux only issue, since your Windows screenshot in the readme seems to have a titlebar icon, but on Linux there is only the default placeholder visible.

When adding the `windowIcon` property to the .ui file, it shows it correctly:
(left is current version, right is with this patch applied)
Screenshot_20220419_212544

same for the taskbar icon:
Screenshot_20220419_212643

### CODE REVIEW

**Comment by dail8859** [comment]
> last PR for today, I hope I am not annoying with all those PRs :P

Not at all! I very much appreciate all the effort. Though I'm familiar with Linux and have used it in the past, its not my main day-to-day OS of choice so I'm glad to have someone willing to improve the Linux side of things!

> I am not sure if this is a Linux only issue

I've never noticed an issue on Windows. It has the title bar icon, task bar icon, etc. It doesn't have the big icon on the help menu but that might be Linux specific.

I want to poke around a bit on Windows before merging to see if I can understand why its Linux specific. Hopefully I'll get to it today 😄

**Comment by dail8859** [comment]
Notes for myself for later. A quick search through the documentation indicates there's several ways to add an icon.

[QWidget::windowIcon()](https://doc.qt.io/qt-5/qwidget.html#windowIcon-prop) documentation:

> This property only makes sense for windows. If no icon has been set, windowIcon() returns the application icon QApplication::windowIcon()).

[QApplication::windowIcon()](https://doc.qt.io/qt-5/qapplication.html#windowIcon-prop) documentation:

> This property holds the default window icon

[QWindow::setIcon()](https://doc.qt.io/qt-5/qwindow.html#setIcon) documentation:

> The window icon might be used by the windowing system for example to decorate the window, and/or in the task switcher.

**Comment by zocker-160** [comment]
I did a bit of testing in Qt and I think I know what is going on here.

If I understand your code correctly, at no point you are actually setting the icon, which means that Windows will use the icon inside the .exe as a fallback.
On Linux however the default Xserver window icon will be used as a fallback.

This also explains, why there is no icon in the about section on Windows, because there Qt uses the windows icon if set.

**Comment by dail8859** [comment]
Yeah that sounds right. Since it worked on Windows I didn't give it another thought :)

**Comment by dail8859** [comment]
> at no point you are actually setting the icon

Just confirmed if I use [QApplication::windowIcon()](https://doc.qt.io/qt-5/qapplication.html#windowIcon-prop) then it sets the icon for the entire application including showing up in the Help menu.

**Comment by dail8859** [comment]
So I think the question is now, does it need to be a full 512x512 png?

It must be doing some massive down-scaling to fit it in a 16x16 icon for the windows title bar. However, everything looks fine...so maybe the concern has no merit.

image

**Comment by zocker-160** [comment]
> So I think the question is now, does it need to be a full 512x512 png?

"need" no, but I think it makes sense, considering that:
- it could look bad in the about window
- many Linux distros (like ElementryOS) use large icons in their taskbar, so anything lower than 512x512 will not look great

both points are not really big deals though imo, if you are concerned, I think a 256x256 or 128x128 could also look "good enough".

**Comment by zocker-160** [comment]
just curious: why do you prefer it "in code" vs the ui file?

**Comment by dail8859** [comment]
> both points are not really big deals though imo

Since there's no known issue with 512x512 and the file size isn't a concern then we'll go with it for now. If there ever is an issue it can be addressed then. I tend to overthink things 😄 

> just curious: why do you prefer it "in code" vs the ui file?

The UI file is for the QMainWindow object, in code I set it on the QApplication object which as far as I know can't be configured with a UI file.

**Comment by dail8859** [comment]
I took the opportunity to do a bit more cleanup, along with generating the PNG directly from the SVG file.

Just want to confirm the call to `setWindowIcon()` I added did fix the icon for Linux, correct?

**Comment by zocker-160** [comment]
> Just want to confirm the call to setWindowIcon() I added did fix the icon for Linux, correct?

Negative in the current state it does not work. The reason is the name. I have uploaded `notepadnext.png` while in the code you reference `NotepadNext.png`

When setting the name correctly it works.

When you generate the png out of the svg, I think you can then remove the png I pushed.

**Comment by dail8859** [comment]
> The reason is the name.

Ah good catch.

**Comment by dail8859** [comment]
Thanks again for the PR!

**Pull request merged**
