### PR TITLE
Add Winget Releaser workflow

### PR DESCRIPTION
**Pull request by sitiom**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

[Notepad Next](https://github.com/microsoft/winget-pkgs/tree/master/manifests/d/dail8859/NotepadNext) is already in Winget, and this workflow will be used to update it.

Before merging this:
1. Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN` (or rename the secret name in the workflow).

example

2. Fork https://github.com/microsoft/winget-pkgs under @dail8859. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Sign the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs) for winget-pkgs as you (the PAT owner) will be a first-time contributor.

If you would like to read about this action further, the documentation is [here](https://bittu.eu.org/docs/wr-intro), and the source code is [here](https://github.com/vedantmgoyal2009/winget-releaser).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser).

### CODE REVIEW

**Comment by dail8859** [comment]
Hi @sitiom 

Thanks for the PR. I'm not very familiar with winget, but it looks like winget is just its own registry and points to the installer file already hosted on GitHub. Correct? The reason I ask is I don't want to start supporting yet another build variations of the application (which makes debugging that much harder), however if it is as simple as using the existing installer, that keeps things simple.

The workflow that publishes the release to WinGet...is that 100% automatic? Or is there a way I can cancel or manually approve a release? The only reason I ask is I manually have to approve Linux FlatHub packages getting released (I've had to cancel them as well https://github.com/flathub/com.github.dail8859.NotepadNext/pull/6) and didn't know if that was possible with WinGet or not. Not a huge issue, just curious.

**Comment by sitiom** [comment]
> Thanks for the PR. I'm not very familiar with winget, but it looks like winget is just its own registry and points to the installer file already hosted on GitHub. Correct? The reason I ask is I don't want to start supporting yet another build variations of the application (which makes debugging that much harder), however if it is as simple as using the existing installer, that keeps things simple.

Correct, it only uses the installer. But Winget detects apps from the already existing apps registry. If you already have installed NotepadNext manually via the installer, Winget will detect that too.

> The workflow that publishes the release to WinGet...is that 100% automatic? Or is there a way I can cancel or manually approve a release? The only reason I ask is I manually have to approve Linux FlatHub packages getting released (I've had to cancel them as well [flathub/com.github.dail8859.NotepadNext#6](https://github.com/flathub/com.github.dail8859.NotepadNext/pull/6)) and didn't know if that was possible with WinGet or not. Not a huge issue, just curious.

The PR is created using your PAT, so you would be the PR author. That basically means you can modify or do anything you want before it gets approved and merged. See examples: [microsoft/winget-pkgs/pulls (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser).

**Comment by dail8859** [comment]
Awesome! Since it reuses the existing installer and has minimal overhead when creating releases I'll give it a go!

When I get some more free-time I'll go through the list of steps above before the next release!

**Comment by dail8859** [comment]
Thanks again for the PR! I hope to do a release in the next couple of days (if I get the free time) and will test it out.

**Comment by sitiom** [comment]
@vedantmgoyal2009 Workflow run failed again https://github.com/dail8859/NotepadNext/actions/runs/2781745771

**Comment by dail8859** [comment]
@sitiom No worries. So nothing on my end of things I need to fix?

**Comment by sitiom** [comment]
> @sitiom No worries. So nothing on my end of things I need to fix?

Nothing other than rerunning the workflow when the bug is fixed. I'll just have to tell you when.

**Comment by sitiom** [comment]
@dail8859 It should be fixed now. Please rerun the failed workflow.

**Comment by dail8859** [comment]
@sitiom Running now: https://github.com/dail8859/NotepadNext/runs/7635489569?check_suite_focus=true

**Comment by dail8859** [comment]
https://github.com/microsoft/winget-pkgs/pull/68461

**Comment by vedantmgoyal2009** [comment]
@dail8859 Sorry for the trouble caused 🙏🏻

**Comment by sitiom** [comment]
Great 🙂 https://github.com/microsoft/winget-pkgs/pull/68461

**Comment by dail8859** [comment]
@vedantmgoyal2009 No worries. Thanks for the help!

**Pull request merged**
